CREATE PROCEDURE "DEYSUB"."TESTGOADAPTER2" (IN first INTEGER, IN second VARCHAR(8)) 
LANGUAGE SQLSCRIPT 
SQL SECURITY INVOKER 
AS 
BEGIN 
	INSERT INTO "DEYSUB"."TESTGOADAPTER" (A,B) VALUES(first,second);
END;