CREATE PROCEDURE "DEYSUB"."TESTGOADAPTER2" (IN first INTEGER, IN second VARCHAR(8), OUT result INTEGER) 
LANGUAGE SQLSCRIPT 
SQL SECURITY INVOKER 
AS 
BEGIN 
	result := first * LENGTH(second); 
	INSERT INTO "DEYSUB"."TESTGOADAPTER" (A,B) VALUES(4,12);
END;